alias: Deurbel - Relais + Xiaomi
description: Alleen afgaan bij echte druk op de deurbel.
triggers:
  - trigger: state
    entity_id: binary_sensor.doorbell_jablotron_doorbell
    to: "on"
  - trigger: state
    entity_id:
      - binary_sensor.ipc_deurbel_breda_visitor
    from:
      - "off"
    to:
      - "on"
conditions:
  - condition: template
    value_template: |
      {{ trigger.from_state.state == 'off' }}
actions:
  - action: switch.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: switch.deurbel_deurbel_relais
  - delay:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 500
  - action: switch.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: switch.deurbel_deurbel_relais
mode: parallel
